### PR TITLE
Use elementary's template

### PR DESCRIPTION
**Pull request by meisenzahl**

### CODE REVIEW

**Comment by NathanBnm** [comment]
Adding the travis.yml file is not enough. @raibtoffoletto  you have to register in Travis CI too if you want to use Continuous Integration (highly recommended). See the wiki here https://github.com/elementary/houston/wiki/Continuous-Integration.

But it seems you're already use it but not correctly according to elementary. Please merge this if you want Houston CI to review pull requests.

**Review by NathanBnm — APPROVED** [review]

**Comment by raibtoffoletto** [comment]
I saw Travis CI was somehow broken during this past week, I didn't have to get to it yet. Will do ASAP. 😉 Thanks for the PR

**Comment by raibtoffoletto** [comment]
So, apparently I had already updated the travis.yml on the unstable and forgot to merge with the master. There are some conflicts and I tried to solve them, but houston is apparently failing to install nodegit at the moment.

`nodegit.target.mk:253: recipe for target 'Release/obj.target/nodegit/src/promise_completion.o' failed
make: *** [Release/obj.target/nodegit/src/promise_completion.o] Error 1
make: Leaving directory '/home/travis/.nvm/versions/node/v12.13.0/lib/node_modules/@elementaryos/houston/node_modules/nodegit/build'
gyp ERR! build error `


**Update**: There is an open issue... I will just wait that to be merged and check the output
https://github.com/elementary/houston/pull/757

**Comment by raibtoffoletto** [comment]
Ok, my bad, when I merged with unstable I didn't noticed there was a workaround for the bug... downgrading node should solve.

```
node_js:
  - 10/*

```

**Pull request merged**
